# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\python_projects\PyQt5\47)Shortcut_App\favorite_table.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_favorite_window(object):
    def setupUi(self, favorite_window):
        favorite_window.setObjectName("favorite_window")
        favorite_window.resize(600, 285)
        self.centralwidget = QtWidgets.QWidget(favorite_window)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(-1, 9, -1, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.favorite_table = QtWidgets.QTableWidget(self.centralwidget)
        self.favorite_table.setStyleSheet("background-color: rgb(113, 113, 113);\n"
"color: rgb(248, 249, 238);")
        self.favorite_table.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.favorite_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.favorite_table.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.favorite_table.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.favorite_table.setObjectName("favorite_table")
        self.favorite_table.setColumnCount(3)
        self.favorite_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.favorite_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.favorite_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.favorite_table.setHorizontalHeaderItem(2, item)
        self.favorite_table.horizontalHeader().setCascadingSectionResizes(True)
        self.favorite_table.horizontalHeader().setHighlightSections(False)
        self.favorite_table.horizontalHeader().setStretchLastSection(True)
        self.gridLayout.addWidget(self.favorite_table, 1, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(55, 25))
        self.label.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label.setStyleSheet("background-color: rgb(165, 147, 135);\n"
"color: rgb(248, 249, 238);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setMinimumSize(QtCore.QSize(55, 25))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_2.setStyleSheet("background-color: rgb(165, 147, 135);\n"
"color: rgb(248, 249, 238);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 2, 1, 1)
        self.keyword_filter = QtWidgets.QLineEdit(self.centralwidget)
        self.keyword_filter.setMinimumSize(QtCore.QSize(45, 25))
        self.keyword_filter.setMaximumSize(QtCore.QSize(16777215, 25))
        self.keyword_filter.setStyleSheet("background-color: rgb(56, 76, 101);\n"
"color: rgb(248, 249, 238);")
        self.keyword_filter.setObjectName("keyword_filter")
        self.gridLayout_2.addWidget(self.keyword_filter, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 4, 1, 1)
        self.linktype_filter = QtWidgets.QComboBox(self.centralwidget)
        self.linktype_filter.setMinimumSize(QtCore.QSize(75, 25))
        self.linktype_filter.setMaximumSize(QtCore.QSize(16777215, 25))
        self.linktype_filter.setStyleSheet("#linktype_filter\n"
"{\n"
"    color: rgb(248, 249, 238);\n"
"    background-color: rgb(56, 76, 101);\n"
"}\n"
"\n"
"#linktype_filter:on\n"
"{\n"
"    color: rgb(248, 249, 238);\n"
"    background-color: rgb(56, 76, 101);\n"
"}\n"
"\n"
"#linktype_filter QListView\n"
"{\n"
"    color: rgb(248, 249, 238);\n"
"    background-color: rgb(76, 96, 121);\n"
"}")
        self.linktype_filter.setObjectName("linktype_filter")
        self.linktype_filter.addItem("")
        self.linktype_filter.addItem("")
        self.linktype_filter.addItem("")
        self.linktype_filter.addItem("")
        self.gridLayout_2.addWidget(self.linktype_filter, 0, 3, 1, 1)
        self.reload_table_btn = QtWidgets.QPushButton(self.centralwidget)
        self.reload_table_btn.setMinimumSize(QtCore.QSize(35, 35))
        self.reload_table_btn.setMaximumSize(QtCore.QSize(35, 35))
        self.reload_table_btn.setStyleSheet("background-color: rgb(165, 147, 135);")
        self.reload_table_btn.setText("")
        self.reload_table_btn.setObjectName("reload_table_btn")
        self.gridLayout_2.addWidget(self.reload_table_btn, 0, 5, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        favorite_window.setCentralWidget(self.centralwidget)

        self.retranslateUi(favorite_window)
        QtCore.QMetaObject.connectSlotsByName(favorite_window)

    def retranslateUi(self, favorite_window):
        _translate = QtCore.QCoreApplication.translate
        favorite_window.setWindowTitle(_translate("favorite_window", "MainWindow"))
        item = self.favorite_table.horizontalHeaderItem(0)
        item.setText(_translate("favorite_window", "名稱"))
        item = self.favorite_table.horizontalHeaderItem(1)
        item.setText(_translate("favorite_window", "類型"))
        item = self.favorite_table.horizontalHeaderItem(2)
        item.setText(_translate("favorite_window", "連結"))
        self.label.setText(_translate("favorite_window", "關鍵字"))
        self.label_2.setText(_translate("favorite_window", "類型"))
        self.linktype_filter.setItemText(0, _translate("favorite_window", "全部"))
        self.linktype_filter.setItemText(1, _translate("favorite_window", "網頁"))
        self.linktype_filter.setItemText(2, _translate("favorite_window", "資料夾"))
        self.linktype_filter.setItemText(3, _translate("favorite_window", "檔案"))
        self.reload_table_btn.setToolTip(_translate("favorite_window", "重新整理"))
