# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\python_projects\PyQt5\47)Shortcut_App\setting_table.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_App_Setting_Window(object):
    def setupUi(self, App_Setting_Window):
        App_Setting_Window.setObjectName("App_Setting_Window")
        App_Setting_Window.resize(576, 420)
        App_Setting_Window.setStyleSheet("#centralwidget {\n"
"background-color: rgb(56, 76, 101);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(App_Setting_Window)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.path_groupbox = QtWidgets.QGroupBox(self.centralwidget)
        self.path_groupbox.setStyleSheet("QGroupBox {\n"
"    font: 700 11pt \"Microsoft JhengHei UI\";\n"
"    background-color: rgb(248, 249, 238);\n"
"    border-radius: 2px;\n"
"    padding-top: 20px;\n"
"    padding-left: 2px;\n"
"}\n"
"\n"
"QGroupBox::title{\n"
"    font: 700 11pt \"Microsoft JhengHei UI\";\n"
"    background-color: rgb(145, 127, 115);\n"
"    color: rgb(255, 255, 255);\n"
"    padding: 2px;\n"
"    border-radius: 2px;\n"
"}")
        self.path_groupbox.setObjectName("path_groupbox")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.path_groupbox)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_9 = QtWidgets.QLabel(self.path_groupbox)
        self.label_9.setMinimumSize(QtCore.QSize(60, 25))
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_9.setStyleSheet("background-color: rgb(113, 113, 113);\n"
"color: rgb(255, 255, 255);\n"
"padding: 2px;\n"
"border-radius: 2px")
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_2.addWidget(self.label_9)
        self.link_path = QtWidgets.QLineEdit(self.path_groupbox)
        self.link_path.setMaximumSize(QtCore.QSize(16777215, 25))
        self.link_path.setStyleSheet("background-color: rgb(204, 203, 201);")
        self.link_path.setObjectName("link_path")
        self.horizontalLayout_2.addWidget(self.link_path)
        self.setting_link_path_btn = QtWidgets.QPushButton(self.path_groupbox)
        self.setting_link_path_btn.setMaximumSize(QtCore.QSize(25, 25))
        self.setting_link_path_btn.setStyleSheet("background-color: rgb(165, 147, 135);\n"
"color: rgb(255, 255, 255);")
        self.setting_link_path_btn.setObjectName("setting_link_path_btn")
        self.horizontalLayout_2.addWidget(self.setting_link_path_btn)
        self.gridLayout_8.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.path_groupbox)
        self.size_groupbox = QtWidgets.QGroupBox(self.centralwidget)
        self.size_groupbox.setStyleSheet("QGroupBox {\n"
"    font: 700 11pt \"Microsoft JhengHei UI\";\n"
"    background-color: rgb(248, 249, 238);\n"
"    border-radius: 2px;\n"
"    padding-top: 20px;\n"
"    padding-left: 2px;\n"
"}\n"
"\n"
"QGroupBox::title{\n"
"    font: 700 11pt \"Microsoft JhengHei UI\";\n"
"    background-color: rgb(145, 127, 115);\n"
"    color: rgb(255, 255, 255);\n"
"    padding: 2px;\n"
"    border-radius: 2px;\n"
"}")
        self.size_groupbox.setObjectName("size_groupbox")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.size_groupbox)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.main_icon_size = QtWidgets.QSpinBox(self.size_groupbox)
        self.main_icon_size.setMinimumSize(QtCore.QSize(70, 25))
        self.main_icon_size.setMaximumSize(QtCore.QSize(70, 25))
        self.main_icon_size.setStyleSheet("background-color: rgb(204, 203, 201);")
        self.main_icon_size.setAlignment(QtCore.Qt.AlignCenter)
        self.main_icon_size.setMaximum(200)
        self.main_icon_size.setProperty("value", 75)
        self.main_icon_size.setObjectName("main_icon_size")
        self.gridLayout_4.addWidget(self.main_icon_size, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.size_groupbox)
        self.label.setMinimumSize(QtCore.QSize(60, 25))
        self.label.setStyleSheet("background-color: rgb(113, 113, 113);\n"
"color: rgb(255, 255, 255);\n"
"padding: 2px;\n"
"border-radius: 2px")
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 0, 0, 1, 1)
        self.sub_icon_size = QtWidgets.QSpinBox(self.size_groupbox)
        self.sub_icon_size.setMinimumSize(QtCore.QSize(70, 25))
        self.sub_icon_size.setMaximumSize(QtCore.QSize(70, 25))
        self.sub_icon_size.setStyleSheet("background-color: rgb(204, 203, 201);")
        self.sub_icon_size.setAlignment(QtCore.Qt.AlignCenter)
        self.sub_icon_size.setMaximum(200)
        self.sub_icon_size.setProperty("value", 50)
        self.sub_icon_size.setObjectName("sub_icon_size")
        self.gridLayout_4.addWidget(self.sub_icon_size, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.size_groupbox)
        self.label_2.setMinimumSize(QtCore.QSize(60, 25))
        self.label_2.setStyleSheet("background-color: rgb(113, 113, 113);\n"
"color: rgb(255, 255, 255);\n"
"padding: 2px;\n"
"border-radius: 2px")
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 0, 2, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.size_groupbox)
        self.pos_groupbox = QtWidgets.QGroupBox(self.centralwidget)
        self.pos_groupbox.setStyleSheet("QGroupBox {\n"
"    font: 700 11pt \"Microsoft JhengHei UI\";\n"
"    background-color: rgb(248, 249, 238);\n"
"    border-radius: 2px;\n"
"    padding-top: 20px;\n"
"    padding-left: 2px;\n"
"}\n"
"\n"
"QGroupBox::title{\n"
"    font: 700 11pt \"Microsoft JhengHei UI\";\n"
"    background-color: rgb(145, 127, 115);\n"
"    color: rgb(255, 255, 255);\n"
"    padding: 2px;\n"
"    border-radius: 2px;\n"
"}")
        self.pos_groupbox.setObjectName("pos_groupbox")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.pos_groupbox)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_4 = QtWidgets.QLabel(self.pos_groupbox)
        self.label_4.setMinimumSize(QtCore.QSize(45, 25))
        self.label_4.setStyleSheet("background-color: rgb(113, 113, 113);\n"
"color: rgb(255, 255, 255);\n"
"padding: 2px;\n"
"border-radius: 2px")
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.pos_x = QtWidgets.QSpinBox(self.pos_groupbox)
        self.pos_x.setMinimumSize(QtCore.QSize(70, 25))
        self.pos_x.setMaximumSize(QtCore.QSize(70, 25))
        self.pos_x.setStyleSheet("background-color: rgb(204, 203, 201);")
        self.pos_x.setAlignment(QtCore.Qt.AlignCenter)
        self.pos_x.setMaximum(9999)
        self.pos_x.setProperty("value", 1000)
        self.pos_x.setObjectName("pos_x")
        self.gridLayout_2.addWidget(self.pos_x, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.pos_groupbox)
        self.label_5.setMinimumSize(QtCore.QSize(45, 25))
        self.label_5.setStyleSheet("background-color: rgb(113, 113, 113);\n"
"color: rgb(255, 255, 255);\n"
"padding: 2px;\n"
"border-radius: 2px")
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 1, 0, 1, 1)
        self.pos_y = QtWidgets.QSpinBox(self.pos_groupbox)
        self.pos_y.setMinimumSize(QtCore.QSize(70, 25))
        self.pos_y.setMaximumSize(QtCore.QSize(70, 25))
        self.pos_y.setStyleSheet("background-color: rgb(204, 203, 201);")
        self.pos_y.setAlignment(QtCore.Qt.AlignCenter)
        self.pos_y.setMaximum(9999)
        self.pos_y.setProperty("value", 50)
        self.pos_y.setObjectName("pos_y")
        self.gridLayout_2.addWidget(self.pos_y, 1, 1, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_3 = QtWidgets.QLabel(self.pos_groupbox)
        self.label_3.setMinimumSize(QtCore.QSize(50, 25))
        self.label_3.setStyleSheet("background-color: rgb(113, 113, 113);\n"
"color: rgb(255, 255, 255);\n"
"padding: 2px;\n"
"border-radius: 2px")
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 0, 1, 1)
        self.main_distance = QtWidgets.QSpinBox(self.pos_groupbox)
        self.main_distance.setMinimumSize(QtCore.QSize(70, 25))
        self.main_distance.setMaximumSize(QtCore.QSize(70, 25))
        self.main_distance.setStyleSheet("background-color: rgb(204, 203, 201);")
        self.main_distance.setAlignment(QtCore.Qt.AlignCenter)
        self.main_distance.setMaximum(100)
        self.main_distance.setProperty("value", 25)
        self.main_distance.setObjectName("main_distance")
        self.gridLayout_3.addWidget(self.main_distance, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.pos_groupbox)
        self.label_7.setMinimumSize(QtCore.QSize(50, 25))
        self.label_7.setStyleSheet("background-color: rgb(113, 113, 113);\n"
"color: rgb(255, 255, 255);\n"
"padding: 2px;\n"
"border-radius: 2px")
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 1, 0, 1, 1)
        self.sub_distance = QtWidgets.QSpinBox(self.pos_groupbox)
        self.sub_distance.setMinimumSize(QtCore.QSize(70, 25))
        self.sub_distance.setMaximumSize(QtCore.QSize(70, 25))
        self.sub_distance.setStyleSheet("background-color: rgb(204, 203, 201);")
        self.sub_distance.setAlignment(QtCore.Qt.AlignCenter)
        self.sub_distance.setMaximum(100)
        self.sub_distance.setProperty("value", 25)
        self.sub_distance.setObjectName("sub_distance")
        self.gridLayout_3.addWidget(self.sub_distance, 1, 1, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_3, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem1, 0, 2, 1, 1)
        self.verticalLayout.addWidget(self.pos_groupbox)
        self.function_groupbox = QtWidgets.QGroupBox(self.centralwidget)
        self.function_groupbox.setStyleSheet("QGroupBox {\n"
"    font: 700 11pt \"Microsoft JhengHei UI\";\n"
"    background-color: rgb(248, 249, 238);\n"
"    border-radius: 2px;\n"
"    padding-top: 20px;\n"
"    padding-left: 2px;\n"
"}\n"
"\n"
"QGroupBox::title{\n"
"    font: 700 11pt \"Microsoft JhengHei UI\";\n"
"    background-color: rgb(145, 127, 115);\n"
"    color: rgb(255, 255, 255);\n"
"    padding: 2px;\n"
"    border-radius: 2px;\n"
"}")
        self.function_groupbox.setObjectName("function_groupbox")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.function_groupbox)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_8 = QtWidgets.QLabel(self.function_groupbox)
        self.label_8.setMinimumSize(QtCore.QSize(0, 25))
        self.label_8.setStyleSheet("background-color: rgb(113, 113, 113);\n"
"color: rgb(255, 255, 255);\n"
"padding: 2px;\n"
"border-radius: 2px")
        self.label_8.setObjectName("label_8")
        self.gridLayout_7.addWidget(self.label_8, 1, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem2, 0, 2, 1, 1)
        self.sub_ani_period = QtWidgets.QSpinBox(self.function_groupbox)
        self.sub_ani_period.setMinimumSize(QtCore.QSize(70, 25))
        self.sub_ani_period.setMaximumSize(QtCore.QSize(70, 25))
        self.sub_ani_period.setStyleSheet("background-color: rgb(204, 203, 201);")
        self.sub_ani_period.setAlignment(QtCore.Qt.AlignCenter)
        self.sub_ani_period.setMaximum(1000)
        self.sub_ani_period.setSingleStep(10)
        self.sub_ani_period.setProperty("value", 100)
        self.sub_ani_period.setObjectName("sub_ani_period")
        self.gridLayout_7.addWidget(self.sub_ani_period, 1, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.function_groupbox)
        self.label_6.setMinimumSize(QtCore.QSize(0, 25))
        self.label_6.setStyleSheet("background-color: rgb(113, 113, 113);\n"
"color: rgb(255, 255, 255);\n"
"padding: 2px;\n"
"border-radius: 2px")
        self.label_6.setObjectName("label_6")
        self.gridLayout_7.addWidget(self.label_6, 0, 0, 1, 1)
        self.main_ani_period = QtWidgets.QSpinBox(self.function_groupbox)
        self.main_ani_period.setMinimumSize(QtCore.QSize(70, 25))
        self.main_ani_period.setMaximumSize(QtCore.QSize(70, 25))
        self.main_ani_period.setStyleSheet("background-color: rgb(204, 203, 201);")
        self.main_ani_period.setAlignment(QtCore.Qt.AlignCenter)
        self.main_ani_period.setMaximum(1000)
        self.main_ani_period.setSingleStep(10)
        self.main_ani_period.setProperty("value", 250)
        self.main_ani_period.setObjectName("main_ani_period")
        self.gridLayout_7.addWidget(self.main_ani_period, 0, 1, 1, 1)
        self.is_auto_hide = QtWidgets.QCheckBox(self.function_groupbox)
        self.is_auto_hide.setMinimumSize(QtCore.QSize(0, 25))
        self.is_auto_hide.setStyleSheet("background-color: rgb(113, 113, 113);\n"
"color: rgb(255, 255, 255);\n"
"padding: 2px;\n"
"border-radius: 2px")
        self.is_auto_hide.setChecked(True)
        self.is_auto_hide.setObjectName("is_auto_hide")
        self.gridLayout_7.addWidget(self.is_auto_hide, 2, 0, 1, 1)
        self.isopenlink_byclicktable = QtWidgets.QCheckBox(self.function_groupbox)
        self.isopenlink_byclicktable.setMinimumSize(QtCore.QSize(0, 25))
        self.isopenlink_byclicktable.setStyleSheet("background-color: rgb(113, 113, 113);\n"
"color: rgb(255, 255, 255);\n"
"padding: 2px;\n"
"border-radius: 2px")
        self.isopenlink_byclicktable.setChecked(True)
        self.isopenlink_byclicktable.setObjectName("isopenlink_byclicktable")
        self.gridLayout_7.addWidget(self.isopenlink_byclicktable, 2, 1, 1, 1)
        self.verticalLayout.addWidget(self.function_groupbox)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(-1, -1, -1, 10)
        self.verticalLayout_3.setSpacing(25)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.size_groupbox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.size_groupbox_2.setMinimumSize(QtCore.QSize(170, 220))
        self.size_groupbox_2.setStyleSheet("QGroupBox {\n"
"    font: 700 11pt \"Microsoft JhengHei UI\";\n"
"    background-color: rgb(248, 249, 238);\n"
"    border-radius: 2px;\n"
"    padding-top: 20px;\n"
"    padding-left: 2px;\n"
"}\n"
"\n"
"QGroupBox::title{\n"
"    font: 700 11pt \"Microsoft JhengHei UI\";\n"
"    background-color: rgb(145, 127, 115);\n"
"    color: rgb(255, 255, 255);\n"
"    padding: 2px;\n"
"    border-radius: 2px;\n"
"}")
        self.size_groupbox_2.setObjectName("size_groupbox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.size_groupbox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_10 = QtWidgets.QLabel(self.size_groupbox_2)
        self.label_10.setMinimumSize(QtCore.QSize(60, 35))
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 35))
        self.label_10.setStyleSheet("background-color: rgb(113, 113, 113);\n"
"color: rgb(255, 255, 255);\n"
"padding: 2px;\n"
"border-radius: 2px")
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_5.addWidget(self.label_10)
        self.main_icon_label = QtWidgets.QLabel(self.size_groupbox_2)
        self.main_icon_label.setMinimumSize(QtCore.QSize(30, 30))
        self.main_icon_label.setMaximumSize(QtCore.QSize(30, 30))
        self.main_icon_label.setStyleSheet("background-color: rgb(218, 218, 218);")
        self.main_icon_label.setText("")
        self.main_icon_label.setObjectName("main_icon_label")
        self.horizontalLayout_5.addWidget(self.main_icon_label)
        self.main_icon_select_btn = QtWidgets.QPushButton(self.size_groupbox_2)
        self.main_icon_select_btn.setMaximumSize(QtCore.QSize(25, 25))
        self.main_icon_select_btn.setStyleSheet("background-color: rgb(165, 147, 135);\n"
"color: rgb(255, 255, 255);")
        self.main_icon_select_btn.setObjectName("main_icon_select_btn")
        self.horizontalLayout_5.addWidget(self.main_icon_select_btn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.main_icon_path = QtWidgets.QLineEdit(self.size_groupbox_2)
        self.main_icon_path.setMaximumSize(QtCore.QSize(16777215, 0))
        self.main_icon_path.setObjectName("main_icon_path")
        self.verticalLayout_2.addWidget(self.main_icon_path)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_11 = QtWidgets.QLabel(self.size_groupbox_2)
        self.label_11.setMinimumSize(QtCore.QSize(60, 35))
        self.label_11.setMaximumSize(QtCore.QSize(16777215, 35))
        self.label_11.setStyleSheet("background-color: rgb(113, 113, 113);\n"
"color: rgb(255, 255, 255);\n"
"padding: 2px;\n"
"border-radius: 2px")
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_4.addWidget(self.label_11)
        self.favorite_icon_label = QtWidgets.QLabel(self.size_groupbox_2)
        self.favorite_icon_label.setMinimumSize(QtCore.QSize(30, 30))
        self.favorite_icon_label.setMaximumSize(QtCore.QSize(30, 30))
        self.favorite_icon_label.setStyleSheet("background-color: rgb(218, 218, 218);")
        self.favorite_icon_label.setText("")
        self.favorite_icon_label.setObjectName("favorite_icon_label")
        self.horizontalLayout_4.addWidget(self.favorite_icon_label)
        self.favorite_icon_select_btn = QtWidgets.QPushButton(self.size_groupbox_2)
        self.favorite_icon_select_btn.setMaximumSize(QtCore.QSize(25, 25))
        self.favorite_icon_select_btn.setStyleSheet("background-color: rgb(165, 147, 135);\n"
"color: rgb(255, 255, 255);")
        self.favorite_icon_select_btn.setObjectName("favorite_icon_select_btn")
        self.horizontalLayout_4.addWidget(self.favorite_icon_select_btn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.favorite_icon_path = QtWidgets.QLineEdit(self.size_groupbox_2)
        self.favorite_icon_path.setMaximumSize(QtCore.QSize(16777215, 0))
        self.favorite_icon_path.setObjectName("favorite_icon_path")
        self.verticalLayout_2.addWidget(self.favorite_icon_path)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_16 = QtWidgets.QLabel(self.size_groupbox_2)
        self.label_16.setMinimumSize(QtCore.QSize(60, 35))
        self.label_16.setMaximumSize(QtCore.QSize(16777215, 35))
        self.label_16.setStyleSheet("background-color: rgb(113, 113, 113);\n"
"color: rgb(255, 255, 255);\n"
"padding: 2px;\n"
"border-radius: 2px")
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_6.addWidget(self.label_16)
        self.link_icon_label = QtWidgets.QLabel(self.size_groupbox_2)
        self.link_icon_label.setMinimumSize(QtCore.QSize(30, 30))
        self.link_icon_label.setMaximumSize(QtCore.QSize(30, 30))
        self.link_icon_label.setStyleSheet("background-color: rgb(218, 218, 218);")
        self.link_icon_label.setText("")
        self.link_icon_label.setObjectName("link_icon_label")
        self.horizontalLayout_6.addWidget(self.link_icon_label)
        self.link_icon_select_btn = QtWidgets.QPushButton(self.size_groupbox_2)
        self.link_icon_select_btn.setMaximumSize(QtCore.QSize(25, 25))
        self.link_icon_select_btn.setStyleSheet("background-color: rgb(165, 147, 135);\n"
"color: rgb(255, 255, 255);")
        self.link_icon_select_btn.setObjectName("link_icon_select_btn")
        self.horizontalLayout_6.addWidget(self.link_icon_select_btn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.link_icon_path = QtWidgets.QLineEdit(self.size_groupbox_2)
        self.link_icon_path.setMaximumSize(QtCore.QSize(16777215, 0))
        self.link_icon_path.setObjectName("link_icon_path")
        self.verticalLayout_2.addWidget(self.link_icon_path)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_14 = QtWidgets.QLabel(self.size_groupbox_2)
        self.label_14.setMinimumSize(QtCore.QSize(60, 35))
        self.label_14.setMaximumSize(QtCore.QSize(16777215, 35))
        self.label_14.setStyleSheet("background-color: rgb(113, 113, 113);\n"
"color: rgb(255, 255, 255);\n"
"padding: 2px;\n"
"border-radius: 2px")
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_3.addWidget(self.label_14)
        self.setting_icon_label = QtWidgets.QLabel(self.size_groupbox_2)
        self.setting_icon_label.setMinimumSize(QtCore.QSize(30, 30))
        self.setting_icon_label.setMaximumSize(QtCore.QSize(30, 30))
        self.setting_icon_label.setStyleSheet("background-color: rgb(218, 218, 218);")
        self.setting_icon_label.setText("")
        self.setting_icon_label.setObjectName("setting_icon_label")
        self.horizontalLayout_3.addWidget(self.setting_icon_label)
        self.setting_icon_select_btn = QtWidgets.QPushButton(self.size_groupbox_2)
        self.setting_icon_select_btn.setMaximumSize(QtCore.QSize(25, 25))
        self.setting_icon_select_btn.setStyleSheet("background-color: rgb(165, 147, 135);\n"
"color: rgb(255, 255, 255);")
        self.setting_icon_select_btn.setObjectName("setting_icon_select_btn")
        self.horizontalLayout_3.addWidget(self.setting_icon_select_btn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.setting_icon_path = QtWidgets.QLineEdit(self.size_groupbox_2)
        self.setting_icon_path.setMaximumSize(QtCore.QSize(16777215, 0))
        self.setting_icon_path.setObjectName("setting_icon_path")
        self.verticalLayout_2.addWidget(self.setting_icon_path)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.verticalLayout_3.addWidget(self.size_groupbox_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem4 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.save_btn = QtWidgets.QPushButton(self.centralwidget)
        self.save_btn.setMinimumSize(QtCore.QSize(80, 30))
        self.save_btn.setMaximumSize(QtCore.QSize(80, 30))
        self.save_btn.setStyleSheet("background-color: rgb(165, 147, 135);\n"
"color: rgb(255, 255, 255);")
        self.save_btn.setObjectName("save_btn")
        self.horizontalLayout.addWidget(self.save_btn)
        self.reset_btn = QtWidgets.QPushButton(self.centralwidget)
        self.reset_btn.setMinimumSize(QtCore.QSize(80, 30))
        self.reset_btn.setMaximumSize(QtCore.QSize(80, 30))
        self.reset_btn.setStyleSheet("background-color: rgb(165, 147, 135);\n"
"color: rgb(255, 255, 255);")
        self.reset_btn.setObjectName("reset_btn")
        self.horizontalLayout.addWidget(self.reset_btn)
        spacerItem5 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 1, 1, 1)
        self.size_groupbox.raise_()
        self.pos_groupbox.raise_()
        self.save_btn.raise_()
        self.reset_btn.raise_()
        self.function_groupbox.raise_()
        self.path_groupbox.raise_()
        self.size_groupbox_2.raise_()
        self.label_14.raise_()
        self.setting_icon_label.raise_()
        self.favorite_icon_label.raise_()
        self.label_11.raise_()
        self.main_icon_label.raise_()
        self.label_10.raise_()
        App_Setting_Window.setCentralWidget(self.centralwidget)

        self.retranslateUi(App_Setting_Window)
        QtCore.QMetaObject.connectSlotsByName(App_Setting_Window)
        App_Setting_Window.setTabOrder(self.main_icon_size, self.sub_icon_size)
        App_Setting_Window.setTabOrder(self.sub_icon_size, self.pos_x)
        App_Setting_Window.setTabOrder(self.pos_x, self.pos_y)
        App_Setting_Window.setTabOrder(self.pos_y, self.main_distance)
        App_Setting_Window.setTabOrder(self.main_distance, self.sub_distance)
        App_Setting_Window.setTabOrder(self.sub_distance, self.main_ani_period)
        App_Setting_Window.setTabOrder(self.main_ani_period, self.sub_ani_period)
        App_Setting_Window.setTabOrder(self.sub_ani_period, self.save_btn)
        App_Setting_Window.setTabOrder(self.save_btn, self.reset_btn)

    def retranslateUi(self, App_Setting_Window):
        _translate = QtCore.QCoreApplication.translate
        App_Setting_Window.setWindowTitle(_translate("App_Setting_Window", "MainWindow"))
        self.path_groupbox.setTitle(_translate("App_Setting_Window", "路徑設定"))
        self.label_9.setText(_translate("App_Setting_Window", "連結檔案"))
        self.setting_link_path_btn.setText(_translate("App_Setting_Window", "..."))
        self.size_groupbox.setTitle(_translate("App_Setting_Window", "尺寸設定"))
        self.label.setText(_translate("App_Setting_Window", "主Icon 尺寸"))
        self.label_2.setText(_translate("App_Setting_Window", "第二層Icon"))
        self.pos_groupbox.setTitle(_translate("App_Setting_Window", "位置設定"))
        self.label_4.setText(_translate("App_Setting_Window", "X座標"))
        self.label_5.setText(_translate("App_Setting_Window", "Y座標"))
        self.label_3.setText(_translate("App_Setting_Window", "主間距"))
        self.label_7.setText(_translate("App_Setting_Window", "次間距"))
        self.function_groupbox.setTitle(_translate("App_Setting_Window", "功能設定"))
        self.label_8.setText(_translate("App_Setting_Window", "次動畫速度 (毫秒)"))
        self.label_6.setText(_translate("App_Setting_Window", "主動畫速度 (毫秒)"))
        self.is_auto_hide.setText(_translate("App_Setting_Window", "自動收合"))
        self.isopenlink_byclicktable.setText(_translate("App_Setting_Window", "點擊 table 即開啟連結"))
        self.size_groupbox_2.setTitle(_translate("App_Setting_Window", "Icon 設定"))
        self.label_10.setText(_translate("App_Setting_Window", "主程式"))
        self.main_icon_select_btn.setText(_translate("App_Setting_Window", "..."))
        self.label_11.setText(_translate("App_Setting_Window", "我的最愛"))
        self.favorite_icon_select_btn.setText(_translate("App_Setting_Window", "..."))
        self.label_16.setText(_translate("App_Setting_Window", "連結頁"))
        self.link_icon_select_btn.setText(_translate("App_Setting_Window", "..."))
        self.label_14.setText(_translate("App_Setting_Window", "設定頁"))
        self.setting_icon_select_btn.setText(_translate("App_Setting_Window", "..."))
        self.save_btn.setText(_translate("App_Setting_Window", "儲存"))
        self.reset_btn.setText(_translate("App_Setting_Window", "重置"))
